version: "3.9"

services:
  mongo:
    image: mongo
    container_name: gameplay-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./backend
    container_name: gameplay-backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URL=${MONGO_URL}
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
    container_name: gameplay-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongo_data:
